APPS-4242 fix issues related to the glue test suites
spryker/testify pull request #5
Opened 2022-05-20 16:42 UTC by sergeyspryker

2022-05-23 07:44 UTC, stereomon requested changes
Move this change to `spryker/spryker`.

2022-05-23 07:44 UTC, stereomon commented on tests/SprykerTest/Glue/Testify/_support/Helper/AbstractConnection.php
> +     * @param array<string, mixed>|string|object $requestParameters
WOuld be good to add some documentation about when which type will be used.

2022-05-23 07:44 UTC, stereomon commented on tests/SprykerTest/Glue/Testify/_support/Helper/GlueRest.php
> +     * @param array|string|object $parameters
The `array` needs more details with `array<...>`

2022-05-23 07:44 UTC, stereomon commented on tests/SprykerTest/Shared/Testify/_support/Helper/ClassResolverTrait.php
> +    protected function resolveClassName(string $classNamePattern, string $moduleName, ?string $layerName = null): ?string
`layerName` should be `application`. I guess it will be one of Glue, Zed, Yves, etc.

2022-05-23 07:44 UTC, stereomon commented on tests/SprykerTest/Zed/Testify/_support/Helper/Business/BusinessHelper.php
> +    protected const BUSINESS_LAYER_NAME = 'Zed';
Layers are used in Zed we have `Business`, `Communication`, etc. Rename to `APPLICATION_NAME`

2022-11-11 13:35 UTC, dereuromark commented
Closing as this needs to go into above linked repo for further discussion.

2022-11-11 13:35 UTC, closed without merging